### ISSUE TITLE
Compiling tutorial has wrong VS version listed in the instructions

### ISSUE THREAD

**Issue by Draise14** [Bforartists/files#15]
![firefox_2019-01-07_11-56-55](https://user-images.githubusercontent.com/35357409/50781508-8a291d00-1273-11e9-852f-8a053f6aa86e.png)

Tutorial lists VS 2013 instead of VS 2017 in the instructions.

**Comment by Draise14** [comment]
![soffice bin_2019-01-07_11-58-13](https://user-images.githubusercontent.com/35357409/50781552-a62cbe80-1273-11e9-9ed8-014505292563.png)

Fixed

**Comment by ReinerBforartists** [comment]
Not finished yet until uploaded to the webspace i would say :)

**Comment by ReinerBforartists** [comment]
New version is online. Closing.
