### ISSUE TITLE
Compiling tutorial quick tip to update SVN repositories

### ISSUE THREAD

**Issue by Draise14** [Bforartists/files#16]
![soffice bin_2019-01-08_12-03-41](https://user-images.githubusercontent.com/35357409/50846557-7518c080-133d-11e9-9b1b-6f2199489531.png)

Added quick tip to update SVN repositories periodically to avoid building issues.

**Comment by ReinerBforartists** [comment]
Okay, let's make a pdf version and upload it to the server ^^

**Comment by ReinerBforartists** [comment]
New version is online.

Closing.
