### ISSUE TITLE
Tutorial - Building Bforartists - Specify how to do different build types

### ISSUE THREAD

**Issue by Draise14** [Bforartists/files#17]
## Issue
Currently the only way to know how to build a correct release of Bforartists mean we activate Alembic, Open VDB, OpenSubdiv and Oben VDB. But some of these entries have double items to tick off in Cmake and some there is no mention as to how to build a lite version for quick UI prototyping or what is what. Meaning, every time we built, it will be a release build and take from 30 to 45 minutes per build test. 

## Task
It would be good to suggest and show how to make different build settings to manually setup different build types for prototyping in a quicker way.

**Comment by ReinerBforartists** [comment]
This is no task to solve. More a development question. And would fit better into the forum.

Have a look into build_files\cmake\config . There you will find the differen config files. For development it is most of the times good enough to build Bforartists as is, with its default settings. This excludes Cuda, and goes relatively fast.

You can also work with two target folders. The one with just the defaults, the other with all your needed bells and whistles.

When you want to change this defaults, then this would be a task. But i don't see a need for it really. Alembic is already on by default. Open Subdiv and Open VDB is releases features.

Closing.

**Comment by ReinerBforartists** [comment]
Ah you want to update the tutorials here. That's of course a good idea. Reopening ...

**Comment by ReinerBforartists** [comment]
Closing because of too long inactive. We can make a new task in case there is a need for.
