### ISSUE TITLE
Is it not better to use git-lfs in main repo for icons?

### ISSUE THREAD

**Issue by tkaczz** [Bforartists/files#18]
As in title. It will simplify build process.

**Comment by ReinerBforartists** [comment]
Hmmm. the single files in the files repository are not this large yet. And it would be more than one extra step to keep everything in sync, which complicates things. I am not really keen to sync 1400 single icons :D

There is nothing to build here. It's just a file repository to store some content. So i would say we can get away with the current file handling :)

But thanks for the idea :)

**Comment by ReinerBforartists** [comment]
Rereading, and noticed the term main repo XD

Also here, it would complicate things dramatically when we would work with pointers. Yes, the icons and every further change blows up the repository. This is not to prevent. But the price that we would pay with pointers would be too high.

**Comment by tkaczz** [comment]
> Rereading, and noticed the term main repo XD
> 
> Also here, it would complicate things dramatically when we would work with pointers. Yes, the icons and every further change blows up the repository. This is not to prevent. But the price that we would pay with git large file store pointers would be too high.

O I think that this is EOT.
