### ISSUE TITLE
Ubuntu build 

### ISSUE THREAD

**Issue by Joshua-Levine** [Bforartists/files#20]
I'm working on the Ubuntu tutorial. In addition to grammar corrections, I will be taking fresh screenshots. Was it done originally in Ubuntu 17.04 or 17.10?

Also, whoever got the original Ubuntu install running, are you able to work together with me to get a tutorial running on the latest Ubuntu LTS (18.04)?

**Comment by ReinerBforartists** [comment]
This was 17.10. And i fear i am of no big help anymore. This was done at a VM that does not longer exist. I have upgraded my hardware and the os to Win 10 meanwhile ...

But you can post any problem here that you run into. ktotheoz works with Linux, and is surely willing to help out.

**Comment by Joshua-Levine** [comment]
Just knowing what OS version gets me off to a running start. If all goes well, the new file will be headed your way soon.

**Comment by ReinerBforartists** [comment]
The problem with Ubuntu is that it kills old dependencies too fast. And then you are trapped in the dependencies hell. I remember that i ran into an outdated Python version at one point. Ubuntu made it deprecated ...

**Comment by Joshua-Levine** [comment]
I don't know much about code, but wouldn't the LTS version specifically refrain from killing dependencies for the duration of the support?

**Comment by ReinerBforartists** [comment]
Sure. But users don't use lts versions. They usually use the newest versions. And expect the software to work there too. It would not help us ^^

**Comment by Joshua-Levine** [comment]
Well, 17.10 is no help either. I just did a fresh install, and it won't allow me to install git.  I suggest we take down the tutorial until such time that we can come up with a strategy for Ubuntu. I can, of course, fix the grammar on the tutorial we have, but I cannot furnish updated screenshots without the ability to install via 17.10 today.

On the other hand, the Arch repository is working just fine. :-D
![image](https://user-images.githubusercontent.com/57484876/70038294-adae3200-15c0-11ea-9802-866b205ad2eb.png)

**Comment by ReinerBforartists** [comment]
Nice :D

As suggested, skip the Ubuntu 17 tutorial, it was made with Bforartists 1 anyways. If even, go with newest Ubuntu and the current master build.

Corrections at grammar and spelling are nevertheless welcome :)

**Comment by ReinerBforartists** [comment]
Closing. This task is not longer valid.
