### ISSUE TITLE
Clarification needed in Icon tutorial

### ISSUE THREAD

**Issue by Joshua-Levine** [Bforartists/files#21]
"You need to have Blender installed to convert the icons from svg to dat."

Can Bforartists fulfill this function? Or only Blender?
Let me know and I'll make sure the Icon tutorial reflects the answer.

**Comment by ReinerBforartists** [comment]
Blender. The script uses some hardcoded paths that requires Blender 2.79. It will not work with Bforartists. And as far as i know not yet with Blender 2.8x

**Comment by ReinerBforartists** [comment]
Haha, i had completely forgotten about this tasks here, sorry. Three trackers is definitely one too much :D 

Things hasn't changed. It can be that nowadays Blender 2.8x works too. But using 2.79 is still at the safe side.

So i will close this issue now. We will update the tutorial in case 2.79 will ever stop working.
