### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by CyberFoxHax** [Bforartists/files#22]
Any chance we could set up a Discord server for Bbforartists to congregate?

**Comment by ReinerBforartists** [comment]
Hey,

I don't think this is a good idea. For more than one reason. A chat solution means to suggest that you are available for 24/7. Which i personally cannot provide. And our team is too small to even make sure that at least one of us is available for a conversation.

We had a chat for a while. For the very most times i was alone there. And when somebody joined, then i was away. This was a very unsatisfying situation for both sides. And so i closed the chat.

The best place for conversation is the forums and this tracker.

**Comment by CyberFoxHax** [comment]
Very well.

**Comment by Draise14** [comment]
I am on discord most hours of my day (I admin two servers) and try to be active there often. I did suggest a discord live link once. I could be the Bforartists discord admin.. I'm the admin of the official Facebook page and bforartist FB groups already. The activity is low so manageable and it has been nice to answer questions or find user feedback to report to the tracker and/or forum. I know there are many artists who use discord so it would be another portal to grow. To run a server doesn't take away much of my time do I could do this if you want. 

It's best to have these things in one official place early. I know blender has more than half a dozen unofficial servers already... a huge mess. On top of that they use a discord equivalent chat system on another system with Blender Chat. Chaos.

**Comment by ReinerBforartists** [comment]
I have reopened the issue.

I'm really not in the way when you want to have such a place. But i personally will most probably not hang around there.

**Comment by CyberFoxHax** [comment]
Keep me up to date if you do decide to open up a server, or just leave it to @Draise14 since creating a "server" is literally 2 clicks and a name.

**Comment by ReinerBforartists** [comment]
Draise, what do you think? Is this something for you?

**Comment by Draise14** [comment]
Yeah, I'll do it. I'll be the admin and link it to the other socials.

**Comment by Draise14** [comment]
Server created. I'll now make categories and threads in the same structure as the forums. 

Join here: 
https://discord.gg/FWaaCU

**Comment by Draise14** [comment]
![Discord_2020-01-02_08-30-29](https://user-images.githubusercontent.com/35357409/71669283-26c4b480-2d3a-11ea-9e76-3fd331e1dd4a.png)

Ok, server channels created to reflect the forums.

**Comment by Draise14** [comment]
I've also created a developer role, so the developer section is only available to developers. Once you join on @CyberFoxHax , I can also assign you that role to help admin.

**Comment by ReinerBforartists** [comment]
Don't you think it's a bit category overkill? ^^

Anyways, closing this one. Since the task is fulfilled.

**Comment by Draise14** [comment]
Might be, but eh, easier to manage it with forums/tracker if the time comes. Meanwhile.. I'll just populate it and invite people.

**Comment by Draise14** [comment]
Made it more minimal. 

![image](https://user-images.githubusercontent.com/35357409/71672516-2d582980-2d44-11ea-9516-08ed1a399cd4.png)
