### ISSUE TITLE
Logo Font - which is it? 

### ISSUE THREAD

**Issue by Draise14** [Bforartists/files#24]
What is the official logo font? 

For publicity, I have been using MyriadPro and Titillium, and they are included in this repository, but what is the official logo font and font used on the splash screens?

**Comment by ReinerBforartists** [comment]
Woah, i have no idea :D

The logo and the text was once made by davis. All i remember is that it was no standard font, sorry.

**Comment by Draise14** [comment]
![image](https://user-images.githubusercontent.com/35357409/113599900-e3c05380-9604-11eb-84cd-d02fd480f302.png)

I uploaded and organized some fonts (SIL OPEN FONT LICENSE Version 1.1) and another free for use font for the publicity. 

Myriad Pro and Titillium

**Comment by ReinerBforartists** [comment]
Isn't this another issue? :)

**Comment by Draise14** [comment]
Ah, well the font of the logo.. I'll just keep it vector for now. So.. close. Alternative fix here.
