### ISSUE TITLE
Add Sean to have write accest to this repository

### ISSUE THREAD

**Issue by Draise14** [Bforartists/files#25]
# Issue
Sean seems to not to have write access for this repository. 
But he's down to upload a script and other mac based tools or material, possibly even the mac builds to here (instead of dropbox) to help automate the compilation process. 

# Task
Add Seanr
Username is @seanr.

**Comment by ReinerBforartists** [comment]
Will do :)

Uploading mac builds will most probably not work. I remember a file limit of 10 mb for uploads in the tracker.

**Comment by seanr** [comment]
@ReinerBforartists not posting the builds themselves here, but I have a script for actually doing the builds that needs to be shared. ;)

**Comment by ReinerBforartists** [comment]
This is always welcome :)

**Comment by ReinerBforartists** [comment]
Ah, while at it, are you fine with the dropdown solution or shall we search for another upload location for you? I have still an FTP space at my server. I just need to check if it still works, and if guests still have write access.

**Comment by seanr** [comment]
Dropbox is sufficient for now. It was an issue when I didn't have the funds
to maintain the larger plan but that is resolved now.

**Comment by ReinerBforartists** [comment]
Ah, sorry that i did not ask earlier :/

**Comment by seanr** [comment]
NP. Please let me know when you've done this. I'd like to get that stuff pushed up.

**Comment by ReinerBforartists** [comment]
I have sent the request already. You just need to accept . Didn't you receive them? It should be two invitations. I have also added access to the manual repository.

**Comment by seanr** [comment]
Didn't realize that was in my email (I got flooded with crap). Accepted those. Thanks!

**Comment by ReinerBforartists** [comment]
Perfect :)
