### ISSUE TITLE
Tutorial - How to update old files to Bforartists 2.9.0

### ISSUE THREAD

**Issue by Draise14** [Bforartists/files#26]
# Relevant task:
[Document - Warn that any custom template or startup.blend crashes Bforartists Devbuild or Next Official Release #2324](https://github.com/Bforartists/Bforartists/issues/2324)

![TextMaker_ueay3mJbW4](https://user-images.githubusercontent.com/35357409/113599752-ac51a700-9604-11eb-9927-1f5d0b701b41.png)

**Comment by ReinerBforartists** [comment]
Thanks Draise. Please remind me when we release 2.9.0

Mh, just curious, have you checked if this still happens with the newest devbuild? Wasn't there a Blender bug report for that?

**Comment by ReinerBforartists** [comment]
This files have become obsolete. Please remove them.

**Comment by ReinerBforartists** [comment]
Thanks :)
