### ISSUE TITLE
Update Publicity Archive with Facebook campaign images

### ISSUE THREAD

**Issue by Draise14** [Bforartists/files#3]
### Task
Facebook images have been created with *.svg and *.png files and converted to *.jpg to upload to the facebook page. These files need to be backed up and uploaded for later use and as templates for future publicity material. 

**Folders**
- Developer 
- Feature Fix
- Follower Thankyou
- Image of the Day
- Manual Update
- Tip of the Day
- Updates

**Comment by Draise14** [comment]
Now uploading.

**Comment by ReinerBforartists** [comment]
Just that i have said it, here you can also push directly into the master :)

**Comment by ReinerBforartists** [comment]
And another comment, it might be no bad idea to create subfolders in the categories. But time will tell :)

**Comment by Draise14** [comment]
Ah, directly to master? 

I have finished uploading these files/folders. I did create subfolders, to be organized.

**Comment by ReinerBforartists** [comment]
Yes. I don't see big potential for conflicts here. I will most probably never touch this repositroy again ^^
